# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
    # environment:
    #   - AWS_ACCESS_KEY_ID=admin
    #   - AWS_SECRET_ACCESS_KEY=password
---
version: "3"

services:
  spark-iceberg:
    image: tabulario/spark-iceberg:3.4.1
    container_name: spark-iceberg
    networks:
      iceberg_net:
    volumes:
      - ./spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    depends_on:
      - minio
    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      -  minio-data:/data
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  postgres:
    hostname: postgres
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: metastore_db
    networks:
      - iceberg_net

  hive-metastore:
    hostname: hive-metastore
    image: 'hive-metastore:3.2.0'
    container_name: hive
    ports:
      - 9083:9083 # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      - METASTORE_DB_HOSTNAME=postgres
      - METASTORE_TYPE=postgres
    command: "--METASTORE_TYPE postgres"
    depends_on:
      - postgres
    networks:
      - iceberg_net
  trino:
    hostname: trino
    image: 'trinodb/trino:417'
    container_name: trino
    ports:
      - '8090:8080'
    volumes:
      - ./etc:/etc/trino
    networks:
      - iceberg_net
  # mc:
  #   depends_on:
  #     - minio
  #   image: minio/mc
  #   container_name: mc
  #   networks:
  #     iceberg_net:
  #   environment:
  #     - AWS_ACCESS_KEY_ID=admin
  #     - AWS_SECRET_ACCESS_KEY=password
  #   entrypoint: >
  #     /bin/sh -c "
  #     until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
  #     /usr/bin/mc rm -r --force minio/warehouse;
  #     /usr/bin/mc mb minio/warehouse;
  #     /usr/bin/mc policy set public minio/warehouse;
  #     tail -f /dev/null
  #     "
networks:
  iceberg_net:
volumes:
  mariadb-data:
    driver: local
  postgres-data:
    driver: local
  minio-data:
    driver: local
      # - AWS_REGION=us-east-1